id = "rst"
name = "reST"
description = "reST syntax support."
version = "0.0.1"
schema_version = 1
authors = ["elmarco", "stsewd"]
repository = "https://github.com/elmarco/zed-rst"

[grammars.rst]
repository = "https://github.com/stsewd/tree-sitter-rst.git"
commit = "5120f6e59284cb8b85b450bd2db0bd352635ba9f"

[language_servers.esbonio]
name = "Esbonio"
language = "reST"
